---
- hosts: all
  sudo: true
  tasks:
    - name: add group "tomcat"
      group: name=tomcat

    - name: add user "tomcat"
      user: name=tomcatuser group=tomcat home=/usr/share/tomcat7 createhome=no 

    - name: Update Cache
      apt:  update_cache=yes

    - name: Upgrade the System
      apt:  upgrade=dist

    - name: Install Java
      apt:  name=default-jdk state=present

    - name: Install Tomcat
      apt:  name=tomcat7 state=present

    - name: Install Tomcat GUI
      apt:  name=tomcat7-admin state=present

    - name: Install Tomcat Docs
      apt:  name=tomcat7-docs  state=present

    - name: Install Tomcat Examples
      apt:  name=tomcat7-examples state=present

    - name: Change ownership of Tomcat installation
      file: path=/usr/share/tomcat7/ owner=tomcatuser group=tomcat state=directory recurse=yes

    - name: Configure Tomcat users
      template: src=tomcat-users.xml dest=/etc/tomcat7

    - name: Restart the Tomcat server
      service: name=tomcat7 state=restarted
